
targets: ["teff1", "teff2", "teff_ratio", "q", "T0cos", "T0sin", "radius1", 
    "radius2", "mass1", "mass2", "sma", "rsma", "incl", "vgamma", "ecc",
    "eccsin", "ecccos", "k1", "k2", "rsma1", "rsma2"]

target_to_model_type:
  radius1: tf_model
  radius2: tf_model
  mass1: tf_model
  mass2: tf_model
  teff1: pt_model
  teff2: pt_model
  teff_ratio: pt_model
  rsma: tf_model
  q: tf_model
  sma: pt_model
  ecc: tf_model
  T0cos: tf_model
  T0sin: tf_model
  incl: pt_model
  vgamma: tf_model
  eccsin: tf_model
  ecccos: tf_model
  k1: tf_model
  k2: tf_model
  rsma1: tf_model
  rsma2: tf_model


lcflux:
  - Kepler_mean
  - TESS_T
  - Johnson_U
  - Johnson_B
  - Johnson_V
  - Johnson_R
  - Johnson_I
  - Johnson_J
  - Johnson_H
  - Johnson_K
  - Cousins_R
  - Cousins_I
  - SDSS_u
  - SDSS_g
  - SDSS_r
  - SDSS_i
  - SDSS_z
  - SDSS_uprime
  - SDSS_gprime
  - SDSS_rprime
  - SDSS_iprime
  - SDSS_zprime
  - Gaia_BP
  - Gaia_G
  - Gaia_RP
  - Gaia_RVS
  - PanStarrs_g
  - PanStarrs_r
  - PanStarrs_w
  - PanStarrs_open
  - PanStarrs_i
  - PanStarrs_z
  - PanStarrs_y
  - Stromgren_u
  - Stromgren_v
  - Stromgren_b
  - Stromgren_y
  - LSST_u
  - LSST_g
  - LSST_r
  - LSST_i
  - LSST_z
  - LSST_y3
  - SWASP_default
  - ZTF_g
  - ZTF_r
  - ZTF_i
  - Tycho_B
  - Tycho_V
  - Hipparcos_Hp

lwa:
  - 5978.14
  - 7452.64
  - 3551.05
  - 4369.53
  - 5467.57
  - 6695.83
  - 8568.89
  - 12350.0
  - 16620.0
  - 21590.0
  - 6357.35
  - 7828.65
  - 3608.04
  - 4671.78
  - 6141.12
  - 7457.89
  - 8922.78
  - 3542.1
  - 4723.59
  - 6201.71
  - 7672.59
  - 10500.61
  - 5035.75
  - 5822.39
  - 7619.96
  - 8578.16
  - 4810.16
  - 6155.47
  - 5980.7
  - 6431.87
  - 7503.03
  - 8668.36
  - 9613.6
  - 3447.09
  - 4110.6
  - 4663.33
  - 5472.44
  - 3751.2
  - 4740.66
  - 6172.34
  - 7500.97
  - 8678.9
  - 9711.82
  - 5451.75
  - 4746.48
  - 6366.38
  - 7829.03
  - 4280.0
  - 5340.0
  - 4901.7

colflux:
  - GALEX.FUV
  - GALEX.NUV
  - Johnson.U
  - SDSS.u
  - Cousins.U
  - Cousins.B
  - Johnson.B
  - SDSS.g
  - PAN-STARRS.PS1.g
  - GAIA.GAIA3.Gbp
  - Cousins.V
  - Johnson.V
  - SDSS.r
  - PAN-STARRS.PS1.r
  - Cousins.R
  - GAIA.GAIA3.G
  - Johnson.R
  - SDSS.i
  - PAN-STARRS.PS1.i
  - Cousins.I
  - GAIA.GAIA3.Grp
  - PAN-STARRS.PS1.z
  - Johnson.I
  - SDSS.z
  - PAN-STARRS.PS1.y
  - 2MASS.J
  - 2MASS.H
  - 2MASS.Ks
  - WISE.W1
  - WISE.W2
  - WISE.W3

colwa:
  - 1538.6207014101276
  - 2315.6631043370066
  - 3531.050228310502
  - 3561.7887353001856
  - 3605.0710493441597
  - 4413.083819849874
  - 4426.993865030675
  - 4718.872246248685
  - 4866.450566153741
  - 5317.485413571473
  - 5512.103907737096
  - 5537.155963302755
  - 6185.194476741525
  - 6214.6332251010535
  - 6469.439215118383
  - 6724.458843817864
  - 6939.51690821256
  - 7499.704174464691
  - 7544.570864938457
  - 7885.587064676616
  - 7972.387233893862
  - 8679.495604486132
  - 8778.219533275713
  - 8961.488333992429
  - 9633.336065790518
  - 12412.1362416409
  - 16497.14508978023
  - 21909.165926612906
  - 34002.551861150176
  - 46520.081762929745
  - 128075.76485642244

photometric_zero_points:
  - 4.6194e-8
  - 2.05634e-8
  - 3.5e-9
  - 8.60588e-9
  - 3.5e-9
  - 6.73e-9
  - 6.73e-9
  - 4.92255e-9
  - 4.62937e-9
  - 4.08e-9
  - 3.58e-9
  - 3.58e-9
  - 2.85425e-9
  - 2.83071e-9
  - 2.24e-9
  - 2.5e-9
  - 1.88e-9
  - 1.94038e-9
  - 1.91728e-9
  - 1.19e-9
  - 1.27e-9
  - 1.44673e-9
  - 9.24e-10
  - 1.35994e-9
  - 1.17434e-9
  - 3.13e-10
  - 1.13e-10
  - 4.28e-11
  - 8.18e-12
  - 2.42e-12
  - 6.52e-14
